<a href="https://colab.research.google.com/github/kykok18/pm-turi2-preprocessing-rizkyfadilah/blob/main/PM_P4_RizkyFadilah_2488010040.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

# Dataset karyawan (sengaja mengandung masalah kualitas)
data = {
    'usia'      : [25, 32, np.nan, 45, 28, 51, 38, np.nan, 29, 41],
    'pendapatan': [4_000_000, 7_500_000, 5_200_000, 12_000_000, 4_800_000,
                   15_000_000, 8_100_000, 6_300_000, np.nan, 9_900_000],
    'pendidikan': ['SMA','S1','SMA','S2','SMA','S2','S1','S1','SMA','S2'],  # ordinal
    'kota'      : ['Bandung','Jakarta','Bandung','Surabaya','Jakarta',
                   'Surabaya','Jakarta','Bandung','Bandung','Jakarta'],    # nominal
    'membeli'   : ['Tidak','Ya','Tidak','Ya','Tidak','Ya','Ya','Tidak','Tidak','Ya']  # target
}
df = pd.DataFrame(data)
df

   usia  pendapatan pendidikan      kota membeli
0  25.0   4000000.0        SMA   Bandung   Tidak
1  32.0   7500000.0         S1   Jakarta      Ya
2   NaN   5200000.0        SMA   Bandung   Tidak
3  45.0  12000000.0         S2  Surabaya      Ya
4  28.0   4800000.0        SMA   Jakarta   Tidak
5  51.0  15000000.0         S2  Surabaya      Ya
6  38.0   8100000.0         S1   Jakarta      Ya
7   NaN   6300000.0         S1   Bandung   Tidak
8  29.0         NaN        SMA   Bandung   Tidak
9  41.0   9900000.0         S2   Jakarta      Ya

# LATIHAN MANDIRI

### 1. Ganti imputasi usia menjadi mean; bandingkan hasilnya.

In [ ]:
df_median = df.copy()
df_median['usia'] = df_median['usia'].fillna(df_median['usia'].median())
df_median['pendapatan'] = df_median['pendapatan'].fillna(df_median['pendapatan'].median())

print("median usia:", df_median['usia'].median())
print("median pendapatan:", df_median['pendapatan'].median())
print(display(df_median))

median usia: 35.0
median pendapatan: 7500000.0

   usia  pendapatan pendidikan      kota membeli
0  25.0   4000000.0        SMA   Bandung   Tidak
1  32.0   7500000.0         S1   Jakarta      Ya
2  35.0   5200000.0        SMA   Bandung   Tidak
3  45.0  12000000.0         S2  Surabaya      Ya
4  28.0   4800000.0        SMA   Jakarta   Tidak
5  51.0  15000000.0         S2  Surabaya      Ya
6  38.0   8100000.0         S1   Jakarta      Ya
7  35.0   6300000.0         S1   Bandung   Tidak
8  29.0   7500000.0        SMA   Bandung   Tidak
9  41.0   9900000.0         S2   Jakarta      Ya

None

In [ ]:
df['usia'] = df['usia'].fillna(df['usia'].mean())
df['pendapatan'] = df['pendapatan'].fillna(df['pendapatan'].mean())

print("median usia:", df['usia'].mean())
print("median pendapatan:", df['pendapatan'].mean())
print(display(df))

median usia: 36.125
median pendapatan: 8088888.88888889

     usia    pendapatan pendidikan      kota membeli
0  25.000  4.000000e+06        SMA   Bandung   Tidak
1  32.000  7.500000e+06         S1   Jakarta      Ya
2  36.125  5.200000e+06        SMA   Bandung   Tidak
3  45.000  1.200000e+07         S2  Surabaya      Ya
4  28.000  4.800000e+06        SMA   Jakarta   Tidak
5  51.000  1.500000e+07         S2  Surabaya      Ya
6  38.000  8.100000e+06         S1   Jakarta      Ya
7  36.125  6.300000e+06         S1   Bandung   Tidak
8  29.000  8.088889e+06        SMA   Bandung   Tidak
9  41.000  9.900000e+06         S2   Jakarta      Ya

None

In [ ]:
print("Median:", df_median['usia'].median())
print("Mean:", df['usia'].mean())

Median: 35.0
Mean: 36.125

### 3. Tambahkan kolom kategorikal baru dan terapkan one-hot encoding.

In [ ]:
X = df.drop(columns=['membeli'])
y = df['membeli']
X['status_karyawan'] = ['Tetap','Kontrak','Tetap','Tetap','Kontrak','Tetap','Kontrak','Tetap','Kontrak','Tetap']

#Encoding kategorikal (ordinal & one-hot).
X['status_karyawan'] = X['status_karyawan'].map({'Tetap':1, 'Kontrak':0})
X['pendidikan'] = X['pendidikan'].map({'SMA':0,'S1':1,'S2':2}) # ordinal
X = pd.get_dummies(X, columns=['kota'], dtype=int) # nominal
y = y.map({'Tidak':0,'Ya':1})
display(X)
display(y)

,usia,pendapatan,pendidikan,status_karyawan,kota_Bandung,kota_Jakarta,kota_Surabaya
0,25.000,4.000000e+06,0,1,1,0,0
1,32.000,7.500000e+06,1,0,0,1,0
2,36.125,5.200000e+06,0,1,1,0,0
3,45.000,1.200000e+07,2,1,0,0,1
4,28.000,4.800000e+06,0,0,0,1,0
5,51.000,1.500000e+07,2,1,0,0,1
6,38.000,8.100000e+06,1,0,0,1,0
7,36.125,6.300000e+06,1,1,1,0,0
8,29.000,8.088889e+06,0,0,1,0,0
9,41.000,9.900000e+06,2,1,0,1,0

0    0
1    1
2    0
3    1
4    0
5    1
6    1
7    0
8    0
9    1
Name: membeli, dtype: int64

### 2. Gunakan MinMaxScaler (0–1) sebagai ganti StandardScaler; tampilkan describe

In [ ]:
#Membagi data (SEBELUM scaling).

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(
X, y, test_size=0.3, random_state=42)

#Penskalaan (fit pada latih, transform pada latih & uji).

from sklearn.preprocessing import MinMaxScaler
num = ['usia','pendapatan','pendidikan']
sc = MinMaxScaler()
X_train[num] = sc.fit_transform(X_train[num])
X_test[num] = sc.transform(X_test[num])  # cegah data leakage

print("X_train setelah MinMaxScaler")
print(display(X_train))

print("X_test setelah MinMaxScaler")
print(display(X_test))

print("X_train describe")
display(X_train[num].describe())

X_train setelah MinMaxScaler

,usia,pendapatan,pendidikan,status_karyawan,kota_Bandung,kota_Jakarta,kota_Surabaya
0,0.00000,0.0000,0.0,1,1,0,0
7,0.55625,0.2875,0.5,1,1,0,0
2,0.55625,0.1500,0.0,1,1,0,0
9,0.80000,0.7375,1.0,1,0,1,0
4,0.15000,0.1000,0.0,0,0,1,0
3,1.00000,1.0000,1.0,1,0,0,1
6,0.65000,0.5125,0.5,0,0,1,0

None
X_test setelah MinMaxScaler

,usia,pendapatan,pendidikan,status_karyawan,kota_Bandung,kota_Jakarta,kota_Surabaya
8,0.20,0.511111,0.0,0,1,0,0
1,0.35,0.437500,0.5,0,0,1,0
5,1.30,1.375000,1.0,1,0,0,1

None
X_train describe

           usia  pendapatan  pendidikan
count  7.000000    7.000000    7.000000
mean   0.530357    0.398214    0.428571
std    0.349971    0.367808    0.449868
min    0.000000    0.000000    0.000000
25%    0.353125    0.125000    0.000000
50%    0.556250    0.287500    0.500000
75%    0.725000    0.625000    0.750000
max    1.000000    1.000000    1.000000

### 4. Jelaskan mengapa fit_transform pada latih tetapi hanya transform pada uji.

Jawab:

it_transform digunakan pada data latih karena data latih digunakan untuk mencari nilai yang dibutuhkan dalam proses scaling. Sedangkan pada data uji cukup menggunakan transform karena data uji hanya mengikuti hasil scaling dari data latih. Hal ini dilakukan supaya tidak terjadi data leakage, yaitu data uji ikut memengaruhi proses pembelajaran.

#REFLEKSI
###1. Mengapa urutan 'split dulu, baru scaling' penting?
####Jawab:
split dulu baru scaling penting supaya data uji tidak ikut memengaruhi proses scaling. Scaling cukup dipelajari dari data latih, sehingga hasil pengujian lebih objektif dan tidak terjadi data leakage.
###2. Kapan label encoding dan kapan one-hot encoding?
####Jawab:
label encoding digunakan untuk data kategorikal yang memiliki urutan, seperti SMA < S1 < S2. Sedangkan one-hot encoding digunakan untuk data kategorikal yang tidak memiliki urutan, seperti Bandung, Jakarta, dan Surabaya.
###3. Apa perbedaan normalisasi dan standardisasi?
####Jawab:
Normalisasi mengubah nilai data ke rentang tertentu, biasanya 0 sampai 1. Sedangkan standardisasi mengubah data berdasarkan rata-rata dan standar deviasi, sehingga data memiliki rata-rata sekitar 0 dan standar deviasi 1.